// Tucson Foodie Partner Restaurants Database
const TUCSON_FOODIE_RESTAURANTS = {
    // 12-month vouchers ($40-100)
    "Commoner & Co": {
        name: "Commoner & Co",
        address: "6960 E Sunrise Dr, Tucson, AZ 85750",
        neighborhood: "Foothills",
        priceRange: "$$",
        cuisine: "Modern American",
        rating: 4.6,
        phone: "(520) 257-1177",
        website: "commonerco.com",
        voucher: { amount: "$40 off", frequency: "every 12 months" },
        features: ["outdoor patio", "full bar", "brunch", "craft cocktails"],
        specialties: ["Buttermilk Fried Chicken", "Short Rib Tacos", "Brunch Burger"],
        dietaryOptions: { glutenFree: true, vegetarian: true, vegan: false }
    },
    "Kingfisher Bar & Grill": {
        name: "Kingfisher Bar & Grill",
        address: "2564 E Grant Rd, Tucson, AZ 85716",
        neighborhood: "Central",
        priceRange: "$$",
        cuisine: "Seafood/American",
        rating: 4.5,
        phone: "(520) 323-7739",
        website: "kingfishertucson.com",
        voucher: { amount: "$40 off", frequency: "every 12 months" },
        features: ["full bar", "happy hour", "oyster bar", "live music"],
        specialties: ["Fresh Oysters", "Fish Tacos", "Seafood Tower"],
        dietaryOptions: { glutenFree: true, vegetarian: true, vegan: true }
    },
    "Zio Peppe": {
        name: "Zio Peppe",
        address: "6502 E Tanque Verde Rd, Tucson, AZ 85715",
        neighborhood: "East Side",
        priceRange: "$$",
        cuisine: "Italian",
        rating: 4.7,
        phone: "(520) 579-0007",
        website: "ziopeppe.com",
        voucher: { amount: "$100 off", frequency: "every 12 months" },
        features: ["outdoor patio", "full bar", "romantic atmosphere", "private dining"],
        specialties: ["Homemade Pasta", "Wood-Fired Pizza", "Osso Buco"],
        dietaryOptions: { glutenFree: true, vegetarian: true, vegan: true }
    },

    // 6-month vouchers ($20)
    "El Charro Café Downtown": {
        name: "El Charro Café Downtown",
        address: "311 N Court Ave, Tucson, AZ 85701",
        neighborhood: "Downtown",
        priceRange: "$",
        cuisine: "Mexican",
        rating: 4.5,
        phone: "(520) 622-1922",
        website: "elcharrocafe.com",
        voucher: { amount: "$20 off", frequency: "every 6 months" },
        features: ["outdoor patio", "full bar", "historic location", "mariachi on weekends"],
        specialties: ["Carne Seca Tacos", "Chimichanga", "Tableside Guacamole"],
        dietaryOptions: { glutenFree: true, vegetarian: true, vegan: false }
    },
    "El Charro Café (Oro Valley)": {
        name: "El Charro Café (Oro Valley)",
        address: "7725 N Oracle Rd, Oro Valley, AZ 85704",
        neighborhood: "Oro Valley",
        priceRange: "$",
        cuisine: "Mexican",
        rating: 4.4,
        phone: "(520) 229-1922",
        website: "elcharrocafe.com",
        voucher: { amount: "$20 off", frequency: "every 6 months" },
        features: ["outdoor patio", "full bar", "family friendly"],
        specialties: ["Carne Seca Tacos", "Chimichanga", "Enchiladas"],
        dietaryOptions: { glutenFree: true, vegetarian: true, vegan: false }
    },
    "El Charro Café Ventana": {
        name: "El Charro Café Ventana",
        address: "6910 E Sunrise Dr, Tucson, AZ 85750",
        neighborhood: "Foothills",
        priceRange: "$",
        cuisine: "Mexican",
        rating: 4.4,
        phone: "(520) 514-1922",
        website: "elcharrocafe.com",
        voucher: { amount: "$20 off", frequency: "every 6 months" },
        features: ["mountain views", "full bar", "patio dining", "private dining room"],
        specialties: ["Carne Seca Tacos", "Fish Tacos", "Tableside Guacamole"],
        dietaryOptions: { glutenFree: true, vegetarian: true, vegan: false }
    },
    "Dante's Kitchen + Cocktails": {
        name: "Dante's Kitchen + Cocktails",
        address: "5755 E River Rd, Tucson, AZ 85750",
        neighborhood: "North Central",
        priceRange: "$$",
        cuisine: "American",
        rating: 4.5,
        phone: "(520) 744-2264",
        website: "danteskitchen.com",
        voucher: { amount: "$20 off + $1 off cocktails", frequency: "every 6 months" },
        features: ["craft cocktails", "happy hour", "outdoor seating", "live music"],
        specialties: ["Braised Short Ribs", "Duck Confit", "Craft Cocktails"],
        dietaryOptions: { glutenFree: true, vegetarian: true, vegan: false }
    },
    "Dominick's Real Italian": {
        name: "Dominick's Real Italian",
        address: "4415 N Campbell Ave, Tucson, AZ 85718",
        neighborhood: "Central",
        priceRange: "$$",
        cuisine: "Italian",
        rating: 4.6,
        phone: "(520) 529-2700",
        website: "dominicksrealitalian.com",
        voucher: { amount: "$20 off", frequency: "every 6 months" },
        features: ["outdoor patio", "full bar", "authentic recipes", "family owned"],
        specialties: ["Chicken Parmigiana", "Homemade Lasagna", "Tiramisu"],
        dietaryOptions: { glutenFree: true, vegetarian: true, vegan: false }
    },
    "Kingston Kitchen": {
        name: "Kingston Kitchen",
        address: "60 E Congress St, Tucson, AZ 85701",
        neighborhood: "Downtown",
        priceRange: "$",
        cuisine: "Caribbean",
        rating: 4.5,
        phone: "(520) 306-2840",
        website: "kingstonkitchentucson.com",
        voucher: { amount: "$20 off", frequency: "every 6 months" },
        features: ["outdoor seating", "full bar", "reggae music", "vibrant atmosphere"],
        specialties: ["Jerk Chicken", "Curry Goat", "Plantain Chips"],
        dietaryOptions: { glutenFree: true, vegetarian: true, vegan: true }
    },
    "Mojo Cuban Kitchen": {
        name: "Mojo Cuban Kitchen",
        address: "7167 E Tanque Verde Rd, Tucson, AZ 85715",
        neighborhood: "East Side",
        priceRange: "$",
        cuisine: "Cuban",
        rating: 4.5,
        phone: "(520) 298-3188",
        website: "mojocubankitchentucson.com",
        voucher: { amount: "$20 off", frequency: "every 6 months" },
        features: ["outdoor patio", "full bar", "live music Friday nights", "colorful decor"],
        specialties: ["Cuban Pork Tacos", "Mojo Chicken", "Cuban Sandwich"],
        dietaryOptions: { glutenFree: true, vegetarian: true, vegan: false }
    },
    "Penca": {
        name: "Penca",
        address: "50 E Broadway Blvd, Tucson, AZ 85701",
        neighborhood: "Downtown",
        priceRange: "$",
        cuisine: "Latin American",
        rating: 4.6,
        phone: "(520) 203-7681",
        website: "pencatucson.com",
        voucher: { amount: "$20 off", frequency: "every 6 months" },
        features: ["outdoor patio", "full bar", "happy hour", "agave-focused cocktails"],
        specialties: ["Tacos de Hongos", "Duck Carnitas Tacos", "Pescado Tacos"],
        dietaryOptions: { glutenFree: true, vegetarian: true, vegan: true }
    },
    "Prep & Pastry": {
        name: "Prep & Pastry",
        address: "3073 N Campbell Ave, Tucson, AZ 85719",
        neighborhood: "Central",
        priceRange: "$",
        cuisine: "American/Brunch",
        rating: 4.7,
        phone: "(520) 326-7737",
        website: "prepandpastry.com",
        voucher: { amount: "$20 off", frequency: "every 6 months" },
        features: ["outdoor patio", "brunch all day", "fresh pastries", "coffee bar"],
        specialties: ["Eggs Benedict", "French Toast", "Fresh Pastries"],
        dietaryOptions: { glutenFree: true, vegetarian: true, vegan: true }
    },
    "Renee's Tucson": {
        name: "Renee's Tucson",
        address: "7065 E Tanque Verde Rd, Tucson, AZ 85715",
        neighborhood: "East Side",
        priceRange: "$$",
        cuisine: "American",
        rating: 4.5,
        phone: "(520) 299-2500",
        website: "reneestucson.com",
        voucher: { amount: "$20 off", frequency: "every 6 months" },
        features: ["outdoor patio", "full bar", "organic ingredients", "farm to table"],
        specialties: ["Organic Salads", "Grass-Fed Burgers", "Seasonal Specials"],
        dietaryOptions: { glutenFree: true, vegetarian: true, vegan: true }
    },
    "Rocco's Little Chicago": {
        name: "Rocco's Little Chicago",
        address: "2707 E Broadway Blvd, Tucson, AZ 85716",
        neighborhood: "Central",
        priceRange: "$",
        cuisine: "Pizza",
        rating: 4.4,
        phone: "(520) 321-1860",
        website: "roccoslittlechicago.com",
        voucher: { amount: "$20 off", frequency: "every 6 months" },
        features: ["deep dish pizza", "full bar", "sports bar", "family friendly"],
        specialties: ["Chicago Deep Dish", "Italian Beef", "Wings"],
        dietaryOptions: { glutenFree: false, vegetarian: true, vegan: false }
    },
    "Tabu": {
        name: "Tabu",
        address: "7090 E Speedway Blvd, Tucson, AZ 85710",
        neighborhood: "East Central",
        priceRange: "$$",
        cuisine: "Global Fusion",
        rating: 4.5,
        phone: "(520) 885-8228",
        website: "tabutucson.com",
        voucher: { amount: "$20 off", frequency: "every 6 months" },
        features: ["outdoor patio", "full bar", "unique atmosphere", "global menu"],
        specialties: ["Fusion Tacos", "Asian Noodles", "Creative Cocktails"],
        dietaryOptions: { glutenFree: true, vegetarian: true, vegan: true }
    },
    "Tavolino Ristorante": {
        name: "Tavolino Ristorante",
        address: "2890 N Swan Rd, Tucson, AZ 85712",
        neighborhood: "Central",
        priceRange: "$$$",
        cuisine: "Italian",
        rating: 4.7,
        phone: "(520) 531-1913",
        website: "tavolinotucson.com",
        voucher: { amount: "$20 off", frequency: "every 6 months" },
        features: ["romantic atmosphere", "wine list", "authentic Italian", "date night"],
        specialties: ["Handmade Pasta", "Veal Marsala", "Wine Selection"],
        dietaryOptions: { glutenFree: true, vegetarian: true, vegan: false }
    },
    "The Monica": {
        name: "The Monica",
        address: "2526 E 6th St, Tucson, AZ 85716",
        neighborhood: "University",
        priceRange: "$",
        cuisine: "Pizza",
        rating: 4.5,
        phone: "(520) 327-7712",
        website: "themonicatucson.com",
        voucher: { amount: "$20 off", frequency: "every 6 months" },
        features: ["wood-fired pizza", "outdoor seating", "craft beer", "casual"],
        specialties: ["Wood-Fired Pizza", "Creative Toppings", "Local Beer"],
        dietaryOptions: { glutenFree: false, vegetarian: true, vegan: true }
    },
    "Tucson Wings": {
        name: "Tucson Wings",
        address: "5966 E Speedway Blvd, Tucson, AZ 85712",
        neighborhood: "East Central",
        priceRange: "$",
        cuisine: "Wings/Sports Bar",
        rating: 4.3,
        phone: "(520) 571-9464",
        website: "tucsonwings.com",
        voucher: { amount: "$20 off", frequency: "every 6 months" },
        features: ["sports bar", "full bar", "TVs", "game day specials"],
        specialties: ["Buffalo Wings", "Specialty Sauces", "Beer Selection"],
        dietaryOptions: { glutenFree: false, vegetarian: false, vegan: false }
    },

    // 90-day vouchers ($10-20)
    "BATA": {
        name: "BATA",
        address: "35 E Toole Ave, Tucson, AZ 85701",
        neighborhood: "Downtown",
        priceRange: "$$",
        cuisine: "Modern American",
        rating: 4.6,
        phone: "(520) 798-2282",
        website: "bataTucson.com",
        voucher: { amount: "$10 off", frequency: "every 90 days" },
        features: ["craft cocktails", "small plates", "trendy atmosphere", "late night"],
        specialties: ["Small Plates", "Craft Cocktails", "Seasonal Menu"],
        dietaryOptions: { glutenFree: true, vegetarian: true, vegan: true }
    },
    "Bubbe's Fine Bagels": {
        name: "Bubbe's Fine Bagels",
        address: "1101 N Wilmot Rd, Tucson, AZ 85712",
        neighborhood: "East Central",
        priceRange: "$",
        cuisine: "Bagels/Deli",
        rating: 4.5,
        phone: "(520) 322-9411",
        website: "bubbesbagels.com",
        voucher: { amount: "$10 off", frequency: "every 90 days" },
        features: ["fresh bagels", "deli", "breakfast all day", "casual"],
        specialties: ["Fresh Bagels", "Lox Sandwich", "Breakfast Sandwiches"],
        dietaryOptions: { glutenFree: false, vegetarian: true, vegan: true }
    },
    "Cafe Francais": {
        name: "Cafe Francais",
        address: "7831 E Wrightstown Rd, Tucson, AZ 85715",
        neighborhood: "East Side",
        priceRange: "$",
        cuisine: "French Bakery",
        rating: 4.6,
        phone: "(520) 886-0760",
        website: "cafefrancaistucson.com",
        voucher: { amount: "$10 off", frequency: "every 90 days" },
        features: ["French pastries", "coffee", "breakfast", "lunch"],
        specialties: ["Croissants", "Quiche", "French Pastries"],
        dietaryOptions: { glutenFree: false, vegetarian: true, vegan: false }
    },
    "Calle Tepa": {
        name: "Calle Tepa",
        address: "6151 E Broadway Blvd, Tucson, AZ 85711",
        neighborhood: "East Side",
        priceRange: "$",
        cuisine: "Mexican",
        rating: 4.4,
        phone: "(520) 305-4600",
        website: "calletepa.com",
        voucher: { amount: "$10 off", frequency: "every 90 days" },
        features: ["outdoor seating", "full bar", "family friendly", "quick service"],
        specialties: ["Street Tacos", "Al Pastor", "Carne Asada"],
        dietaryOptions: { glutenFree: true, vegetarian: true, vegan: false }
    },
    "Corbett's": {
        name: "Corbett's",
        address: "340 N 6th Ave, Tucson, AZ 85705",
        neighborhood: "Downtown",
        priceRange: "$",
        cuisine: "American",
        rating: 4.4,
        phone: "(520) 884-5600",
        website: "corbettstucson.com",
        voucher: { amount: "$10 off", frequency: "every 90 days" },
        features: ["live music", "full bar", "outdoor patio", "local favorite"],
        specialties: ["Burgers", "Sandwiches", "Local Beer"],
        dietaryOptions: { glutenFree: true, vegetarian: true, vegan: false }
    },
    "Ghini's French Caffe": {
        name: "Ghini's French Caffe",
        address: "1803 E Prince Rd, Tucson, AZ 85719",
        neighborhood: "Central",
        priceRange: "$",
        cuisine: "French",
        rating: 4.5,
        phone: "(520) 326-9095",
        website: "ghinisfrenchcaffe.com",
        voucher: { amount: "$15 off", frequency: "every 90 days" },
        features: ["French cuisine", "breakfast", "lunch", "cozy atmosphere"],
        specialties: ["Crepes", "French Toast", "Omelettes"],
        dietaryOptions: { glutenFree: true, vegetarian: true, vegan: false }
    },
    "HUB Restaurant": {
        name: "HUB Restaurant",
        address: "266 E Congress St, Tucson, AZ 85701",
        neighborhood: "Downtown",
        priceRange: "$$",
        cuisine: "American",
        rating: 4.4,
        phone: "(520) 207-8201",
        website: "hubdowntown.com",
        voucher: { amount: "$10 off", frequency: "every 90 days" },
        features: ["ice cream", "full bar", "outdoor patio", "family friendly"],
        specialties: ["Gourmet Burgers", "House-Made Ice Cream", "Craft Beer"],
        dietaryOptions: { glutenFree: true, vegetarian: true, vegan: true }
    },
    "Lindy's on 4th": {
        name: "Lindy's on 4th",
        address: "431 N 4th Ave, Tucson, AZ 85705",
        neighborhood: "Downtown/4th Ave",
        priceRange: "$",
        cuisine: "Burgers",
        rating: 4.3,
        phone: "(520) 207-1280",
        website: "lindyson4th.com",
        voucher: { amount: "$10 off", frequency: "every 90 days" },
        features: ["burgers", "full bar", "late night", "casual"],
        specialties: ["Specialty Burgers", "Tater Tots", "Beer Selection"],
        dietaryOptions: { glutenFree: false, vegetarian: true, vegan: true }
    },
    "Lovin' Spoonfuls": {
        name: "Lovin' Spoonfuls",
        address: "2990 N Campbell Ave, Tucson, AZ 85719",
        neighborhood: "Central",
        priceRange: "$",
        cuisine: "Vegan",
        rating: 4.6,
        phone: "(520) 325-7766",
        website: "lovinspoonfuls.com",
        voucher: { amount: "$10 off", frequency: "every 90 days" },
        features: ["100% vegan", "organic", "healthy options", "juice bar"],
        specialties: ["Vegan Bowls", "Fresh Juices", "Plant-Based Desserts"],
        dietaryOptions: { glutenFree: true, vegetarian: true, vegan: true }
    },
    "Monsoon Chocolate": {
        name: "Monsoon Chocolate",
        address: "2545 E Speedway Blvd, Tucson, AZ 85716",
        neighborhood: "Central",
        priceRange: "$",
        cuisine: "Chocolate/Cafe",
        rating: 4.7,
        phone: "(520) 251-8144",
        website: "monsoonchocolate.com",
        voucher: { amount: "$10 off", frequency: "every 90 days" },
        features: ["artisan chocolate", "coffee", "desserts", "gifts"],
        specialties: ["Craft Chocolate", "Drinking Chocolate", "Pastries"],
        dietaryOptions: { glutenFree: true, vegetarian: true, vegan: true }
    },
    "Nook": {
        name: "Nook",
        address: "3200 E Speedway Blvd, Tucson, AZ 85716",
        neighborhood: "Central",
        priceRange: "$",
        cuisine: "American/Brunch",
        rating: 4.5,
        phone: "(520) 232-7200",
        website: "nooktucson.com",
        voucher: { amount: "$10 off", frequency: "every 90 days" },
        features: ["brunch", "outdoor patio", "cozy atmosphere", "local ingredients"],
        specialties: ["Creative Brunch", "Benedicts", "Cocktails"],
        dietaryOptions: { glutenFree: true, vegetarian: true, vegan: true }
    },
    "Penelope Pizza": {
        name: "Penelope Pizza",
        address: "3071 N Alvernon Way, Tucson, AZ 85712",
        neighborhood: "Central",
        priceRange: "$",
        cuisine: "Pizza",
        rating: 4.4,
        phone: "(520) 793-1600",
        website: "penelopepizza.com",
        voucher: { amount: "$10 off", frequency: "every 90 days" },
        features: ["artisan pizza", "local ingredients", "craft beer", "casual"],
        specialties: ["Artisan Pizza", "Creative Toppings", "Salads"],
        dietaryOptions: { glutenFree: true, vegetarian: true, vegan: true }
    },
    "Postino": {
        name: "Postino",
        address: "5285 E Broadway Blvd, Tucson, AZ 85711",
        neighborhood: "East Central",
        priceRange: "$",
        cuisine: "Wine Bar",
        rating: 4.5,
        phone: "(520) 526-0121",
        website: "postinowinebar.com",
        voucher: { amount: "$10 off", frequency: "every 90 days" },
        features: ["wine bar", "bruschetta", "outdoor patio", "happy hour"],
        specialties: ["Bruschetta Board", "Wine Selection", "Paninis"],
        dietaryOptions: { glutenFree: true, vegetarian: true, vegan: true }
    },
    "Vera Earl Premium Beef": {
        name: "Vera Earl Premium Beef",
        address: "121 E Congress St, Tucson, AZ 85701",
        neighborhood: "Downtown",
        priceRange: "$$$",
        cuisine: "Steakhouse",
        rating: 4.6,
        phone: "(520) 344-2275",
        website: "veraearl.com",
        voucher: { amount: "$20 off", frequency: "every 90 days" },
        features: ["premium steaks", "full bar", "upscale", "special occasions"],
        specialties: ["Dry-Aged Steaks", "Seafood", "Wine List"],
        dietaryOptions: { glutenFree: true, vegetarian: false, vegan: false }
    },

    // Monthly vouchers ($5-25)
    "Brooklyn's Beers & Burger": {
        name: "Brooklyn's Beers & Burger",
        address: "7125 E Tanque Verde Rd, Tucson, AZ 85715",
        neighborhood: "East Side",
        priceRange: "$",
        cuisine: "Burgers",
        rating: 4.3,
        phone: "(520) 751-1772",
        website: "brooklynstucson.com",
        voucher: { amount: "$10 off", frequency: "monthly" },
        features: ["burgers", "craft beer", "sports bar", "casual"],
        specialties: ["Gourmet Burgers", "Craft Beer", "Wings"],
        dietaryOptions: { glutenFree: false, vegetarian: true, vegan: false }
    },
    "Mariscos Chihuahua (6th Ave)": {
        name: "Mariscos Chihuahua (6th Ave)",
        address: "1001 N Grande Ave, Tucson, AZ 85705",
        neighborhood: "West Side",
        priceRange: "$",
        cuisine: "Mexican Seafood",
        rating: 4.5,
        phone: "(520) 623-3563",
        website: "mariscoschihuahua.com",
        voucher: { amount: "$10 off", frequency: "monthly" },
        features: ["seafood", "Mexican", "casual", "family owned"],
        specialties: ["Seafood Tacos", "Ceviche", "Mariscos Tower"],
        dietaryOptions: { glutenFree: true, vegetarian: false, vegan: false }
    },
    "Mariscos Chihuahua (Ina)": {
        name: "Mariscos Chihuahua (Ina)",
        address: "4011 W Ina Rd, Tucson, AZ 85741",
        neighborhood: "Northwest",
        priceRange: "$",
        cuisine: "Mexican Seafood",
        rating: 4.5,
        phone: "(520) 572-1233",
        website: "mariscoschihuahua.com",
        voucher: { amount: "$10 off", frequency: "monthly" },
        features: ["seafood", "Mexican", "casual", "family owned"],
        specialties: ["Seafood Tacos", "Ceviche", "Aguachile"],
        dietaryOptions: { glutenFree: true, vegetarian: false, vegan: false }
    },
    "Salad Nation": {
        name: "Salad Nation",
        address: "3420 E Speedway Blvd, Tucson, AZ 85716",
        neighborhood: "Central",
        priceRange: "$",
        cuisine: "Salads",
        rating: 4.4,
        phone: "(520) 318-5160",
        website: "saladnationtucson.com",
        voucher: { amount: "$10 off", frequency: "monthly" },
        features: ["healthy options", "build your own", "fresh ingredients", "quick service"],
        specialties: ["Custom Salads", "Grain Bowls", "Fresh Juices"],
        dietaryOptions: { glutenFree: true, vegetarian: true, vegan: true }
    },
    "Thunder Bacon Burger Co": {
        name: "Thunder Bacon Burger Co",
        address: "7330 E Broadway Blvd, Tucson, AZ 85710",
        neighborhood: "East Central",
        priceRange: "$",
        cuisine: "Burgers",
        rating: 4.2,
        phone: "(520) 885-1908",
        website: "thunderbaconburger.com",
        voucher: { amount: "$5 off", frequency: "monthly" },
        features: ["bacon focus", "burgers", "casual", "quick service"],
        specialties: ["Bacon Burgers", "Bacon Mac & Cheese", "Milkshakes"],
        dietaryOptions: { glutenFree: false, vegetarian: false, vegan: false }
    },
    "Transit Tea": {
        name: "Transit Tea",
        address: "411 N 4th Ave, Tucson, AZ 85705",
        neighborhood: "Downtown/4th Ave",
        priceRange: "$",
        cuisine: "Tea House",
        rating: 4.6,
        phone: "(520) 770-1166",
        website: "transittea.com",
        voucher: { amount: "$5 off", frequency: "monthly" },
        features: ["tea house", "light meals", "study spot", "vegan options"],
        specialties: ["Loose Leaf Tea", "Tea Lattes", "Vegan Treats"],
        dietaryOptions: { glutenFree: true, vegetarian: true, vegan: true }
    },
    "Whole Slvce Pizza": {
        name: "Whole Slvce Pizza",
        address: "50 S Houghton Rd, Tucson, AZ 85748",
        neighborhood: "Southeast",
        priceRange: "$",
        cuisine: "Pizza",
        rating: 4.3,
        phone: "(520) 439-5090",
        website: "wholeslvcepizza.com",
        voucher: { amount: "25% off", frequency: "monthly" },
        features: ["NY style pizza", "by the slice", "casual", "quick service"],
        specialties: ["NY Style Pizza", "Creative Slices", "Garlic Knots"],
        dietaryOptions: { glutenFree: false, vegetarian: true, vegan: true }
    }
};

// Export for use in main app
window.TUCSON_FOODIE_RESTAURANTS = TUCSON_FOODIE_RESTAURANTS;